### ISSUE TITLE
Make robots on *.go-vip.co domains great again

### ISSUE THREAD

**Issue by mdrovdahl** [Automattic/vip-go-mu-plugins#502] opened 2017-03-09 21:32 UTC
About a year ago, VIP Go implemented a (nginx?) rule which forces robots.txt for *.go-vip.co sites to:

```
location = /robots.txt {
       return 200 "User-agent: *\nDisallow: /";
   }
```

This is opaque and there's no feedback to alert an end-user why their robots.txt mods aren't working. Arguably most non-prod sites using a *.go-vip.co domain will want this setting, but it should at least be done in vip-go-mu-plugins for transparency and in the off chance that someone wants to filter it.

**Comment by joshbetz** [comment] 2017-03-13 17:44
I agree that this should be more transparent, but I don't think we want to allow go-vip.co domains to be indexed. Moving this to mu-plugins would make that harder to enforce. What if we added a comment to this robots.txt instead to explain that it's hardcoded for go-vip.co domains?

```
# Indexing is blocked for all go-vip.co domains
User-agent: *
Disallow: /
```

**Comment by simonwheatley** [comment] 2017-08-16 13:55
Related problem: As more sites use custom domains (i.e. not having the forced `robots.txt` protection), we run the risk of us and/or the client team missing the need to protect the site and having content indexed by robots. 

How about we remove the Nginx `location` block (which is creating the output at `robots.txt`, and add something in MU plugins which sends an `X-Robots-Tag: noindex` header late in the template redirect action hook for any non-production sites. We could add a strong warning about this hook about removing it without putting something similar in place.

Thoughts @joshbetz @mjangda @mdrovdahl ?

**Comment by nickdaugherty** [comment] 2017-08-16 16:27
+1 for getting this out of nginx and into MU Plugins where it's visible, reproducible locally, and filterable.

**Comment by mdrovdahl** [comment] 2019-04-16 21:23
@simonwheatley I'm "Spring cleaning"...does this issue serve purpose? Or, should we close it an move on with our lives?

**Comment by simonwheatley** [comment] 2019-04-23 10:18
I think it would spark joy to solve this. Let's leave it, but feel free to unsubscribe (if you can).

**Comment by rebeccahum** [comment] 2022-08-05 20:01
Looks like this has been resolved at https://github.com/Automattic/vip-go-mu-plugins/pull/911.

**Closed by rebeccahum** 2022-08-05 20:01 UTC
Labels: [Type] Enhancement
