### ISSUE TITLE
PURGE requests to preview URLs

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-go-mu-plugins#266] opened 2016-08-11 15:40 UTC
PURGE requests like this have been seen in the wild:

```
PURGE http://somesite.go-vip.co?p=12345&preview_id=12345/feed/ HTTP/1.1
```

The URL format, specifically the `preview_id` query arg, looks like it may be [related to Edit Flow](https://github.com/Automattic/Edit-Flow/blob/f8209f679377a09102c04c92054a36275a2d2294/modules/custom-status/custom-status.php#L1607).

**Comment by rebeccahum** [comment] 2022-08-05 19:30
@simonwheatley Can you elaborate what the potential harm is for these occurrences? And do they occur enough?

**Comment by mjangda** [comment] 2022-08-17 01:55
I think the issue is that there's no need to send PURGE requests to these URLs.

However, given the age, I think we can just close this.

**Closed by mjangda** 2022-08-17 01:55 UTC
Labels: [Status] Has Feedback
