### ISSUE TITLE
Add 'GitHub Access Request' form to Dashboard

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#187] opened 2016-05-06 16:45 UTC
Much like the dotcom SVN access request form, we should do the same for GH access requests.

**Comment by simonwheatley** [comment] 2017-03-04 06:42
Related/duplicate of https://github.com/Automattic/vip-dashboard/issues/53

**Comment by mjangda** [comment] 2018-08-09 03:09
This should probably go into Parker instead.

**Closed by mjangda** 2018-08-09 03:09 UTC
Labels: [Type] Enhancement
