### ISSUE TITLE
PURGE varnish when home_url changes

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-go-mu-plugins#91] opened 2015-12-04 23:07 UTC

**Comment by nickdaugherty** [comment] 2019-05-16 00:53
If the domain is changing, then presumably requests will be going to that new url, which in itself will cause cache invalidations. Purging the old domain wouldn't have a large effect, right?

**Comment by nickdaugherty** [comment] 2019-05-16 01:07
Actually this is the same as #528. Since that one has more details (the issue is potential redirect loops), let's close this in favor of that one.

**Closed by nickdaugherty** 2019-05-16 01:07 UTC
Labels: [Feature] Cache
