### ISSUE TITLE
Provide way to calculate file size of media under VIP Go Files Service

### ISSUE THREAD

**Issue by TheCrowned** [Automattic/vip-go-mu-plugins#952] opened 2018-08-08 15:50 UTC
Since media don't live on the local file system, calls to `filesize()` fail. To reproduce, try this out on Tumbleweed:
```
wp shell
$path = get_attached_file( 14779 );
filesize( $path ); //will return false
```

[This is also the way WP Core populates](https://core.trac.wordpress.org/browser/tags/4.9.8/src/wp-includes/media.php#L3149) the `File size` field in the `Attachment Details` window - see the empty `File size` label on the right

We should
1. Provide a function to get image filesize, maybe adapting [this method](https://stackoverflow.com/questions/2602612/php-remote-file-size-without-downloading-file)?
2. Filter out the Attachment Details, so that the size is shown. Take advantage of the following filter:
`return apply_filters( 'wp_prepare_attachment_for_js', $response, $attachment, $meta );`

**Comment by mjangda** [comment] 2018-08-08 16:02
Duplicate of #695

**Closed** 2018-08-08 16:04 UTC
