### ISSUE TITLE
Getting  `PHP Parse error:  syntax error, unexpected '?'` 

### ISSUE THREAD

**Issue by BhargavBhandari90** [Automattic/vip-go-mu-plugins#829] opened 2018-01-30 11:19 UTC
Getting the error for the below line.

https://github.com/Automattic/vip-go-mu-plugins/blob/6d9c735c14142b422c961985581cbec24fc82c2b/vip-mail.php#L103

**Comment by simonwheatley** [comment] 2018-01-30 12:26
@BhargavBhandari90 Thanks for filing an issue. What version of PHP are you running, please? Is this error occurring in web requests, or WP CLI?

**Comment by BhargavBhandari90** [comment] 2018-01-30 17:49
@simonwheatley My php version: `PHP Version 5.6.32-1+ubuntu16.04.1` and it's occurring in web request only.

**Comment by simonwheatley** [comment] 2018-01-30 18:37
If you are developing for our VIP Go platform you should be using PHP 7.0.x, please. I'm going to close this as won't fix, because I suspect the problem is the PHP version. Please re-open if you find changing the PHP version does not fix it.

**Closed by simonwheatley** 2018-01-30 18:37 UTC
Labels: wontfix

**Comment by BhargavBhandari90** [comment] 2018-01-31 11:21
Thank you @simonwheatley . You are right. :smile:
