### ISSUE TITLE
Theme plugins don't show as activated in admin UI if they are loaded in code

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/vip-go-mu-plugins#106] opened 2015-12-21 23:37 UTC
This plugin is loaded in code, but the Plugins UI shows:

https://cloudup.com/c7SLMT5E-Np

This is because we're just printing the core plugins table here, instead of a custom one that includes logic for plugins loaded in code.

See #105

**Comment by cfg** [comment] 2016-05-27 14:15
This one concerns me a bit, because of how easy it is to accidentally take down a site by not realizing a plugin is loaded, and clicking Activate. In theory, every plugin should be written well enough to prevent that, but in practice this isn't true. Examples of this can be found in nearly any the deprecated plugins being moved from vip/plugins into individual themes.

**Comment by rebeccahum** [comment] 2022-08-05 18:23
Closing out because on attempting to reproduce, I get `Enabled via code` when accessing `plugins.php?plugin_status=all&paged=1&s`. So, this no longer seems to be an issue AFAIK.

Attempted reproduction steps were following the logic in https://docs.wpvip.com/how-tos/activate-plugins-through-code/#plugins-in-the-plugins-directory but instead of calling `wpcom_vip_load_plugin()` in `plugin-loader.php`, I called it in a theme.

**Closed by rebeccahum** 2022-08-05 18:23 UTC
Labels: [Type] Bug
